---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amplify Hosting + Main Branch (Amplify Gen 2 Custom Pipeline)'

Parameters:
  RepoUrl:
    Type: String
    Description: The URL of the repository to be used for the Amplify app.
  AppName:
    Type: String
    Default: eldi-web
    Description: The name of the Amplify app.
  BranchName:
    Type: String
    Default: main
    Description: Choose which Branch do you want to use
  GithubSecretPATArn:
    Type: String
    Description: The GitHub Personal Access Token (PAT) secret stored in AWS Secrets Manager.
  AmplifyServiceRoleArn:
    Type: String
    Description: The ARN of the IAM Role that Amplify will use to access AWS resources.
  PublicPrefix:
    Type: String
    Description: The S3 prefix (folder) to store public configuration files.

Resources:

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Ref RepoUrl
      AccessToken: !Sub '{{resolve:secretsmanager:${GithubSecretPATArn}:SecretString:token}}'
      IAMServiceRole: !Ref AmplifyServiceRoleArn
      Platform: WEB_COMPUTE
      AutoBranchCreationConfig:
        EnableAutoBuild: true
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: "/"
          
  MainBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      Stage: PRODUCTION
      EnableAutoBuild: true
      Framework: "Next.js - SSR"
      BuildSpec: |
        version: 1
        applications:
          - appRoot: .
            frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
    
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-amplify-config'
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
    
  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForConfigPrefix
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketName}/${PublicPrefix}*

Outputs:
  AppId:
    Description: "The Amplify App ID"
    Value: !GetAtt AmplifyApp.AppId
  BranchOut:
    Description: "The Amplify Branch Name"
    Value: !Ref BranchName
  BucketNameOut:
    Value: !Ref BucketName
  PublicPrefixOut:
    Value: !Ref PublicPrefix
  PublicUrlPrefix:
    Value: !Sub https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${PublicPrefix}