---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amplify Hosting + main branch (Amplify Gen 2 Custom Pipeline)'

Parameters:
  RepoUrl:
    Type: String
    Description: The URL of the repository to be used for the Amplify app.
  AppName:
    Type: String
    Default: eldi-web
    Description: The name of the Amplify app.
  BranchName:
    Type: String
    Default: main
    Description: Choose which Branch do you want to use
  GithubSecretPATArn:
    Type: String
    Description: The GitHub Personal Access Token (PAT) secret stored in AWS Secrets Manager.

Resources:

  AmplifyParameterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmplifyParameterPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: "*"

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Ref RepoUrl
      AccessToken: !Sub '{{resolve:secretsmanager:${GithubSecretPATArn}:SecretString:token}}'
      AutoBranchCreationConfig:
        EnableAutoBuild: true
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: "/"
          
  MainBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      Stage: PRODUCTION
      EnableAutoBuild: true

  
Outputs:
  AppId: 
    Description: "The Amplify App ID"
    Value: !GetAtt AmplifyApp.AppId
  BranchOut:
    Description: "The Amplify Branch Name"
    Value: !Ref BranchName
    
    